[package]
name = "summercamps"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
wasm-bindgen = "0.2.99"
web-sys = "0.3.76"
yew = { version = "0.21.0", features = ["csr"] }
